Adding Metrics Based Argo Rollouts
redhat-developer-demos/bubbles-progressive-delivery pull request #2
Opened 2023-03-28 13:08 UTC by kdubois

2023-03-28 13:46 UTC, lordofthejars requested changes

2023-03-28 13:46 UTC, lordofthejars commented on scripts/argorollouts/clean.sh
Could you create a new file called `clean-metrics.sh` so the old one still works?

2023-03-28 13:46 UTC, lordofthejars commented on scripts/argorollouts/deploy.sh
Can you rename to `deploy-metrics.sh` so we keep the old one too?

2023-03-28 13:46 UTC, lordofthejars commented on scripts/argorollouts/rolling-to-v2.sh
Can you rename it so we have the original one too?

2023-03-28 14:12 UTC, kdubois commented on scripts/argorollouts/clean.sh
I created a new folder, that makes it less confusing I think

2023-03-29 09:08 UTC, kdubois commented
@lordofthejars can you review again?  If you merge perhaps use squash because there are a lot of commits :D

2023-03-29 12:35 UTC, lordofthejars approved these changes

2023-03-29 12:36 UTC, merged